### PR TITLE
Librem 5 support

### PR DESCRIPTION
**Pull request by dos1**
This is very obviously not mergeable and I probably won't work on it anymore, but it might be a good base for someone to take over and write proper support, so sharing it here.

Instead of producing SD/eMMC image like for PinePhone, this produces an initramfs that can then be booted straight via USB by using uuu.

What's left to do:
- building u-boot with https://source.puri.sm/Librem5/u-boot-builder/
- building kernel tree from https://source.puri.sm/Librem5/linux-next/
- a kernel defconfig that doesn't need modules for USB and SD card reader to function
- better splash images

### CODE REVIEW

**Comment by asriel-danctnix** [comment]
I don't have a Librem5 but it's cool to see non-Pine64 device running Jumpdrive.

**Comment by dos1** [comment]
So turns out I actually went forward and put it into shape that hopefully allows it to get merged :)

**Comment by MartijnBraam** [comment]
Oh cool, seems mostly allright.

Maybe have the L5 target output a .tar.gz containing the required files and a shell script to launch uuu so that can be main target to build this and to have a file to redistribute.

**Comment by craftyguy** [comment]
I think the dtb here should be the one for Birch, since it'll work on r2, r3, r4, right? If this uses the r4 dtb, then it'll only work on Evergreen?

**Comment by dos1** [comment]
It appears @craftyguy got tired of waiting for me and implemented your suggestions by himself - so I just included his branch in this MR (plus some minor adjustments from me).

The only thing left would then be the splash, which - honestly - IMO looks fine the way it is. Feel free to change it if you want though ;)

**Pull request merged**
